// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorios;

#nullable disable

namespace Repositorios.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260606200245_IncidenciaMigracion")]
    partial class IncidenciaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Equipo", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Bandera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Confederacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RankingFifa")
                        .HasColumnType("int");

                    b.HasKey("Nombre");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Dominio.Entidades.Estadio", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Nombre");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("Dominio.Entidades.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CrucesGenerados")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaGenerado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInicioTorneo")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxPartidosPorDia")
                        .HasColumnType("int");

                    b.Property<int>("SemillaFixture")
                        .HasColumnType("int");

                    b.Property<int>("SeparacionEntreFechas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("Dominio.Entidades.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Dominio.Entidades.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("EquipoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoNombre");

                    b.HasIndex("PartidoId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("Dominio.Entidades.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("Dominio.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PeriodistaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodistaId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Dominio.Entidades.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EquipoLocalNombre")
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EquipoVisitanteNombre")
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EsPorPerdedor")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaBloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadioNombre")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int>("GolesLocalAnterior")
                        .HasColumnType("int");

                    b.Property<int>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<int>("GolesVisitanteAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int?>("OrigenLocalId")
                        .HasColumnType("int");

                    b.Property<int?>("OrigenVisitanteId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneResultado")
                        .HasColumnType("bit");

                    b.Property<string>("VencedorNombre")
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalNombre");

                    b.HasIndex("EquipoVisitanteNombre");

                    b.HasIndex("EstadioNombre");

                    b.HasIndex("GrupoId");

                    b.HasIndex("OrigenLocalId");

                    b.HasIndex("OrigenVisitanteId");

                    b.HasIndex("VencedorNombre");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Dominio.Entidades.PosicionesGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiferenciaGoles")
                        .HasColumnType("int");

                    b.Property<string>("EquipoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("GolesContra")
                        .HasColumnType("int");

                    b.Property<int>("GolesFavor")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("PosicionFinal")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoNombre");

                    b.HasIndex("GrupoId");

                    b.ToTable("PosicionesGrupo");
                });

            modelBuilder.Entity("Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contrasena");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Roles");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FixtureEquipos", b =>
                {
                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("EquipoNombre")
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("FixtureId", "EquipoNombre");

                    b.HasIndex("EquipoNombre");

                    b.ToTable("FixtureEquipos");
                });

            modelBuilder.Entity("FixtureEstadios", b =>
                {
                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<string>("EstadioNombre")
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("FixtureId", "EstadioNombre");

                    b.HasIndex("EstadioNombre");

                    b.ToTable("FixtureEstadios");
                });

            modelBuilder.Entity("Dominio.Entidades.Incidencia", b =>
                {
                    b.HasOne("Dominio.Entidades.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoNombre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Partido", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("Dominio.Entidades.LogAuditoria", b =>
                {
                    b.HasOne("Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Entidades.Notificacion", b =>
                {
                    b.HasOne("Dominio.Entidades.Usuario", "Periodista")
                        .WithMany()
                        .HasForeignKey("PeriodistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodista");
                });

            modelBuilder.Entity("Dominio.Entidades.Partido", b =>
                {
                    b.HasOne("Dominio.Entidades.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalNombre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteNombre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioNombre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Grupo", "Grupo")
                        .WithMany("ListaPartidos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Partido", "OrigenLocal")
                        .WithMany()
                        .HasForeignKey("OrigenLocalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Partido", "OrigenVisitante")
                        .WithMany()
                        .HasForeignKey("OrigenVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Entidades.Equipo", "Vencedor")
                        .WithMany()
                        .HasForeignKey("VencedorNombre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Estadio");

                    b.Navigation("Grupo");

                    b.Navigation("OrigenLocal");

                    b.Navigation("OrigenVisitante");

                    b.Navigation("Vencedor");
                });

            modelBuilder.Entity("Dominio.Entidades.PosicionesGrupo", b =>
                {
                    b.HasOne("Dominio.Entidades.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoNombre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Grupo", "Grupo")
                        .WithMany("ListaPosiciones")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("FixtureEquipos", b =>
                {
                    b.HasOne("Dominio.Entidades.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquipoNombre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FixtureEstadios", b =>
                {
                    b.HasOne("Dominio.Entidades.Estadio", null)
                        .WithMany()
                        .HasForeignKey("EstadioNombre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Entidades.Grupo", b =>
                {
                    b.Navigation("ListaPartidos");

                    b.Navigation("ListaPosiciones");
                });

            modelBuilder.Entity("Dominio.Entidades.Partido", b =>
                {
                    b.Navigation("Incidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
